### PR TITLE
Bump dependencies to fix security vulnerabilities

### LINKED ISSUE #13: Security Vulnerabilities with version 1.1.0
image

Open vulnerabilities:

 MongoDB.Driver.Core@2.3.0 > NETStandard.Library@1.6.0 > System.IO.Compression.ZipFile@4.0.1
 MongoDB.Driver.Core@2.3.0 > System.Net.Security@4.0.0

### PR DESCRIPTION
**Pull request by mishamyte**
Hello @jbogard,

Want to use your project as a part of OTLP stack. 
So due to abandonment of existing PR, updated some deps & pipelines.

Closes #13, #14

### CODE REVIEW

**Review by jbogard — APPROVED** [review]

**Comment by jbogard** [comment]
Build failure :(

**Comment by mishamyte** [comment]
Failure caused by a [known issue](https://jira.mongodb.org/browse/CSHARP-3612) on a MongoDB Driver team side. 
It it caused by unmanaged compression libs, used by MongoDB driver.
They say that it is fixed in the next driver release (2.18.0), but I don't have any timelines.

So I'm looking for a workarounds for now, but hope that release will be soon)

**Comment by mishamyte** [comment]
OK. Seems like this problem would be actual if we will change dep from `MongoDB.Driver.Core` to `MongoDB.Driver`.

To be honest, I'm doubt cause this change could be conceptually huge (and the package is `MongoDB.Driver.Core.Extensions.DiagnosticSources`, not `MongoDB.Driver.Extensions.DiagnosticSources`).

I don't know how acceptable it would be.

What do you think, @jbogard ?

**Comment by mishamyte** [comment]
Looked into the `MongoDB.Driver.Core` repository. The supress it with `<NoWarn>NU5100</NoWarn>`, so seems legit)

**Comment by jbogard** [comment]
Ah that makes sense, thanks!

**Comment by mishamyte** [comment]
I think it could be merged.

Also I'm going to investigate is this package up to date or should be adjusted to the latest spec/practices of pckgs and contribute, if it will be needed

**Pull request merged**
